config/routes.rb
Rails.application.routes.draw do
  resources :journals
  resources :dashboards
  resources :tickets do
    resources :dailies
    resources :links
  end

  root 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_many :dailies
    has_many :links
    enum status: [ :open, :pr_opened, :closed ]

    def status_title
        unless status == Ticket.statuses.key(1)
            status.titleize
        else
            status.titleize.sub("Pr", "PR")
        end
    end

    def past_days
        dailies = self.dailies.order(updated_at: :desc).pluck(:updated_at)
        if dailies.size == 0
          0
        else
          end_reference = self.closed? ? dailies.first.to_date : DateTime.now.to_date
          (end_reference -  dailies.last.to_date).to_i
        end
      end
end

app/controllers/tickets_controller.rb
include DateHelper

class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tickets = Ticket.order(:status, "updated_at DESC")
    @today = today
    fifteen_days_ago = (@today - 15.days).to_date

    @last_15_days_tickets = @tickets.filter do |ticket|
      ticket.updated_at.to_date >= fifteen_days_ago
    end

    @tickets -= @last_15_days_tickets

    unless @tickets.find{ |t| !t.closed? }.nil?
      flash[:notice] = "There's a non closed ticket for more than 15 days"
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @last_dailies = @ticket.dailies.order(:status, "updated_at DESC").limit(3)
    @links = @ticket.links
    @daily = Daily.new
    @link = Link.new
  end

  # GET /tasks/new
  def new
    @ticket = Ticket.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.status = Ticket.statuses[:open]

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to tickets_url, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to tickets_url, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:name, :status)
    end
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= form.label :name, class: "form-label" %>
        <div class="input-group">
          <%= form.text_field :name, class: "form-control" %>
          <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="col-4"></div>
    <div class="col-4"></div>
  </div>
<% end %>

app/views/tickets/_form_new_daily.erb
<%= form_with(model: ticket_dailies, url: [@ticket, ticket_dailies]) do |form| %>
  <% if ticket_dailies.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily.errors.count, "error") %> prohibited this daily from being saved:</h2>

      <ul>
        <% @daily.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :notes, class: "form-label" %>
    <%= form.text_area :notes, class: "form-control" %>
  </div>

  <br>

  <div class="actions d-grid gap-2">
    <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tickets/_form_new_link.erb
<%= form_with(model: link, url: [@ticket, link], class: "row g-3") do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-auto">
    <label for="staticEmail2" class="visually-hidden">Email</label>
  </div>

  <div class="col-auto">
    <%= form.text_field :label, class: "form-control", placeholder: :label %>
  </div>

  <div class="col-auto">
    <%= form.text_field :url, class: "form-control", placeholder: :url %>
  </div>

  <div class="col-auto">
    <%= form.submit 'Salvar', :class => "btn btn-primary mb-3" %>
  </div>
<% end %>

app/views/tickets/_form_status_update.erb
 <div class="horizontal-radio-group">
    <%= form_with(model: @ticket) do |f| %>
        <% Ticket.statuses.map(&:first).each do |status| %>
            <%= f.radio_button :status, status, checked: (@ticket.status == status), :onclick => "this.parentNode.submit();", :class => "horizontal-radio-button"  %>
            <%= f.label ("status_" + status), status.titleize, :class=>"horizontal-radio-button-label" %>
        <% end %>    
    <% end %>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @task %> |

app/views/tickets/index.html.erb
<% unless notice == nil %>
  <div class="alert alert-primary alert-dismissible fade show" style="margin-top: 16px; margin-bottom: 16px;"role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<br/>
<h1>Tickets</h1>
<hr>

<%= link_to 'Novo ticket', new_ticket_path, class: "btn btn-primary" %>
<br><br>

<h3>Worked in the last 15 days - <span class="badge bg-primary"><%= @last_15_days_tickets.size %> tickets</span></h3>

<table class="table table-striped bg-white">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th class="text-center" scope="col">Status</th>
      <th class="text-center" scope="col">Last update</th>
    </tr>
  </thead>

  <tbody>
    <% @last_15_days_tickets.each do |ticket| %>
      <tr>
        <td class="vertical-middle"><%= link_to ticket.name, ticket %></td>
        <td class="text-center vertical-middle"><%= bs_status_badge ticket %> </td>
        <td class="text-center vertical-middle"><%= date_difference_in_words(ticket.updated_at, @today) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<h3>
  Other tickets <span class="badge bg-primary"><%= @tickets.size %> tickets</span> &nbsp;
  <a data-bs-toggle="collapse" href="#otherticketscollapse" role="button" aria-expanded="false" aria-controls="otherticketscollapse">
    <i class="fa-solid fa-plus"></i>
    <i class="fa-solid fa-minus"></i>
  </a>
</h3> 

<div class="collapse multi-collapse" id="otherticketscollapse">
  <table class="table table-striped bg-white">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th class="text-center" scope="col">Status</th>
        <th class="text-center" scope="col">Last update</th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td class="vertical-middle"><%= link_to ticket.name, ticket %></td>
          <td class="text-center vertical-middle"><%= bs_status_badge ticket %> </td>
          <td class="text-center vertical-middle"><%= (date_ty_simplifier ticket.updated_at).capitalize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/new.html.erb
<h1>Novo Ticket</h1>

<%= render 'form', ticket: @ticket %>

<br>

<%= link_to 'Voltar', tickets_path, :class => 'btn btn-primary' %>

app/views/tickets/show.html.erb
<h1 class="text-center"><%= @ticket.name %>
  <span onclick="copyToClipboard('<%= @ticket.name %>', 'ticketcopyicon', 'fa-copy');" ><i id="ticketcopyicon" class="far fa-copy fa-xs" ></i></span>
</h1> 
<h3 class="text-center"><%= @ticket.past_days %> dias </h3>
<% unless notice == nil %>
  <div class="alert alert-primary alert-dismissible fade show" style="margin-top: 16px; margin-bottom: 16px;"role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>


<%= render 'form_status_update' %>

<br /><br />

<h3>Links 
  <a class="btn btn-primary btn-sm" data-bs-toggle="collapse" href="#collapseNewLink" role="button" aria-expanded="false" aria-controls="collapseNewLink">Add</a>
  <%= link_to "Show All", ticket_links_url(@ticket), class: "btn btn-primary btn-sm" %>
</h3>

<div class="collapse" id="collapseNewLink">
  <%= render 'form_new_link', link: @link %>
</div> <br/>

<% unless @links.size == 0 %>
  <br />
  <ul class="list-group list-group-horizontal">
    <% @links.each do |link| %>
      <li class="list-group-item"><%= link_to link.label, link.url, target: "_blank" %> </li>
    <% end %>
  </ul>
<% end %>
</ul>

<br /><br />

<h3>Dailies 
  <a class="btn btn-primary btn-sm" data-bs-toggle="collapse" href="#collapseNewDaily" role="button" aria-expanded="false" aria-controls="collapseNewDaily">Add</a>
  <%= link_to "Show All", ticket_dailies_url(@ticket), class: "btn btn-primary btn-sm" %>
</h3>

<div class="collapse" id="collapseNewDaily">
  <%= render 'form_new_daily', ticket_dailies: @daily %>
</div> <br/>

<table class="table table-striped bg-white">
  <thead>
    <tr>
      <th scope="col" class="text-center">Date/Time</th>
      <th scope="col">Note</th>
    </tr>
  </thead>

  <tbody>
    <% @last_dailies.each do |daily| %>
      <tr>
        <td class="text-center"> 
          <%= daily.updated_at.strftime("%d/%m - %H:%M") %></td>
        <td><%= link_to daily.notes_truncated, ticket_daily_url(@ticket.id, daily) %></td>
      </tr>
    <% end %>
  </tbody>
</table>