config/routes.rb
Rails.application.routes.draw do
  resources :journals
  resources :dashboards
  resources :tickets do
    resources :dailies
    resources :links
  end

  root 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :ticket
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :check_ticket

  # GET /links or /links.json
  def index
    @links = Link.where(ticket_id: params[:ticket_id])
    @link = Link.new
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to ticket_links_url(@ticket), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to ticket_links_url(@ticket), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to ticket_links_url(@ticket), notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end
    
    def check_ticket
      @ticket = Ticket.where(id: params[:ticket_id]).first
      if @ticket.nil?
        respond_to do |format|
          format.html { redirect_to tickets_path, notice: "Ticket does not exist." }
          format.json { render :index, status: :unprocessable_entity }
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).merge(ticket_id: @ticket.id).permit(:ticket_id, :label, :url)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, url: [@ticket, link], class: "row g-3") do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-auto">
    <label for="staticEmail2" class="visually-hidden">Email</label>
  </div>

  <div class="col-auto">
    <%= form.text_field :label, class: "form-control", placeholder: :label %>
  </div>

  <div class="col-auto">
    <%= form.text_field :url, class: "form-control", placeholder: :url %>
  </div>

  <div class="col-auto">
    <%= form.submit 'Salvar', :class => "btn btn-primary mb-3" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', :back, class: "btn btn-primary btn-sm" %>

app/views/links/index.html.erb
<% unless notice == nil %>
  <div class="alert alert-primary alert-dismissible fade show" style="margin-top: 16px; margin-bottom: 16px;"role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>


<h1 class="text-center">Links - <%= link_to @ticket.name, @ticket %></h1>

<br />
<%= render 'form', link: @link %>
<br />

<% unless @links.size == 0 %>
  <table class="table table-striped bg-white">
    <thead>
      <tr>
        <th scope="col">Label</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td class="vertical-middle"><%= link.label %></td>
          <td><%= link_to 'Edit', edit_ticket_link_path(@ticket, link), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to 'Destroy', ticket_link_url(@ticket, link), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<br>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @link.ticket %>
</p>

<p>
  <strong>Label:</strong>
  <%= @link.label %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>