config/routes.rb
Rails.application.routes.draw do
  resources :journals
  resources :dashboards
  resources :tickets do
    resources :dailies
    resources :links
  end

  root 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/journal.rb
class Journal < ApplicationRecord
    enum radio_values: [ :bad, :medium, :good ]
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]
  before_action :reference_dates, only: %i[ index edit ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.where(updated_at: [@month_first_day.beginning_of_day..(@month_last_day.end_of_day)])
    @today_journal = @journals.select{ |j| j.updated_at.to_date == @today.to_date }.first
    
    @calendar_days = get_calendar_days

    @business_days = @month_days.filter{ |d| d.wday > 0 && d.wday < 6 }.size

    @show_next_month = @today.month != @reference_date.month

    @show_previous_month = (Journal.order(:updated_at).limit(1).pluck(:updated_at).first == nil) ?  false : (@reference_date.month != (Journal.order(:updated_at).limit(1).pluck(:updated_at).first.month))

    @progress_bar_width = @journals.size * 100 / @business_days

  end

  # GET /journals/1 or /journals/1.json
  def show
    respond_to do |format|
      format.js{ render layout: false}
    end
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
    if Journal.find(params[:id].to_i).updated_at.to_date != @reference_date.to_date
      respond_to do |format|
        format.html { redirect_to journals_url, notice: "Não se pode editar um journal diferente do dia de hoje" }
      end
    end
  end

  # POST /journals or /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to journals_path, notice: "Journal was successfully created." }
        format.json { render :index, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to journals_path, notice: "Journal was successfully updated." }
        format.json { render :index, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Journal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    IS_MONTH = /^(0?[1-9]|1[012])$/
    IS_INTEGER = /\A\d+\z/

    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:meetings, :current_task, :team_interaction, :humor, :comments)
    end

    def reference_dates
      @today = Date.today
      @reference_date = (!valid_param_month || !valid_param_year || (params[:m].to_i == @today.month && params[:y].to_i == @today.year)) ? @today : Date.new(params[:y].to_i, params[:m].to_i, 1)
      @month_first_day = @reference_date.beginning_of_month
      @month_last_day = @reference_date.end_of_month

      @month_days = ((@month_first_day)..( @month_last_day)).to_a
      
      @previous_month = (@month_first_day - 1)
      @next_month = (@month_last_day + 1)
    end

    def get_calendar_days
       last_month_days = @month_first_day.wday == 0 ? [] : (((@month_first_day - (@month_first_day.wday))..@month_first_day).to_a)[0...-1]
       next_month_days = @month_last_day.wday == 6 ? [] : (( (@month_last_day + 1)..( @month_last_day + (6 -  @month_last_day.wday))).to_a)

       calendar_days = last_month_days + @month_days + next_month_days

       (calendar_days.each_slice(7)).to_a
    end

    def valid_param_month
      (params[:m] != nil && params[:m] =~ IS_MONTH)
    end

    def valid_param_year
      (params[:y] != nil && params[:y] =~ IS_INTEGER && params[:y].size == 4)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper

    def calendar_class_chain(day, reference_date, today, journals)
        classes = ""
        event_days = journals.map{|j| j.updated_at.to_date }
        
        if day.wday == 0 || day.wday == 6
            classes += " weekend-day"
        end

        if reference_date.month == day.month - 1
            classes += " next-month"
        elsif reference_date.month == day.month + 1
            classes += " prev-month"
        else
            if event_days.include?(day.to_date) 
                # to simplify just show journals from this month
                classes += " event"
            end
            
        end

        if day == reference_date && reference_date == today
            classes += " current-day"
        end
        classes
    end

    def get_journal_from_day(day, journals)
        journals.select{ |j| j.updated_at.to_date == day.to_date }.first
    end

    def get_journal_topic_icon scale
        case scale
        when 0
            "fa-regular fa-face-frown fa-2xl"
        when 1
            "fa-regular fa-face-meh fa-2xl"
        else
            "fa-regular fa-face-smile fa-2xl"
        end
    end
end

app/views/journals/_calendar_day.erb
<% classes = calendar_class_chain(day, @reference_date, @today, @journals) %>

<% if classes.size == 0 %>
    <td><%= day.day %></td>
<% else %>
    <td class="<%= classes %>">
        <% if day.to_date == @today.to_date && @reference_date.month == day.month %>
            <% if @today_journal == nil %>
                <%= link_to (day.day.to_s), new_journal_path %>
            <% else %>
                <%= link_to (day.day.to_s), edit_journal_path(@today_journal) %>
            <% end %>
        <% elsif day.month == @reference_date.month %>
            <% journal_from_day = get_journal_from_day(day, @journals)%>
            <%= journal_from_day == nil ? day.day.to_s : (link_to( (day.day.to_s), journal_from_day, remote: true))  %>
        <% else %>
            <%= day.day.to_s %>
        <% end %>
    </td>
<% end %>

app/views/journals/_form.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <%= form_with(model: journal) do |form| %>
      <% if journal.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

          <ul>
            <% journal.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <%= render 'journal_radio_group', form: form, field: :meetings %>
        <%= render 'journal_radio_group', form: form, field: :current_task %>
        <%= render 'journal_radio_group', form: form, field: :team_interaction %>
        <%= render 'journal_radio_group', form: form, field: :humor %>
      </div>

      <br>  

      <div class="form-group">
        <%= form.label :comments, class: "form-label" %>
        <%= form.text_area :comments, class: "form-control big-text-area" %>
      </div>

      <br>
      <div class="actions d-grid gap-2">
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/journals/_journal_radio_group.erb
  <div class="form-group p-2 bg-light border rounded-3 journal-cb-group-box bg-white">
    <p><%= form.label field %></p>
    <div class="form-check form-check-inline">
      <%= form.radio_button field, 0, class: "form-check-input" %>
      <%= form.label :bad, class: "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= form.radio_button field, 1, class: "form-check-input" %>
      <%= form.label :medium, class: "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= form.radio_button field, 2, class: "form-check-input" %>
      <%= form.label :good, class: "form-check-label" %>
    </div>    
    
  </div>

  <br /> 

app/views/journals/_journal_show.html.erb
<div class="modal fade" id="journalModal" tabindex="-1" aria-labelledby="modal-journal-title" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-journal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-journal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/journals/_show.html.erb
<div class="p-5 mb-4 rounded-3">
  <div class="container-fluid py-5">
    <div class="row">
      <div class="col">
        <p class="text-center">Meetings</p>
        <p class="text-center"><i class="<%= get_journal_topic_icon  journal.meetings %>"></i></p>
      </div>
      <div class="col">
        <p class="text-center">Current task</p>
        <p class="text-center"><i class="<%= get_journal_topic_icon  journal.current_task %>"></i></p>
      </div>
      <div class="col">
        <p class="text-center">Team interaction</p>
        <p class="text-center"><i class="<%= get_journal_topic_icon  journal.team_interaction %>"></i></p>
      </div>
      <div class="col">
        <p class="text-center">Humor</p>
        <p class="text-center"><i class="<%= get_journal_topic_icon  journal.humor %>"></i></p>
      </div>
    </div><br /><br />
    <div class="row">
      <%= journal.comments %>
    </div>
  </div>
</div>

app/views/journals/edit.html.erb
<br/>
<h1 class="text-center">Editing Journal</h1>

<%= render 'form', journal: @journal %>

app/views/journals/index.html.erb
<% unless notice == nil %>
  <div class="alert alert-primary alert-dismissible fade show" style="margin-top: 16px; margin-bottom: 16px;"role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<br/>

<%= render 'journal_show' %>
<div class="d-flex justify-content-center ">
  <div class="calendar">

    <header>
      <!-- Month name -->
      <h2><%= @reference_date.strftime("%B").capitalize %></h2>
      <% if @show_previous_month %>
        <%= link_to "", journals_path(:m => @previous_month.month, :y => @previous_month.year), :class  => "btn-prev fa-solid fa-angle-left" %>
      <% end %>
      <% if @show_next_month %>
        <%= link_to "", journals_path(:m => @next_month.month, :y => @next_month.year), :class  => "btn-next fa-solid fa-angle-right" %>
      <% end %>
      <p> <%= @business_days %> dias uteis</p>

      <div class="progress mt-4 d-flex">
          <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= @progress_bar_width %>%" aria-valuenow="<%= @progress_bar_width  %>" aria-valuemin="0" aria-valuemax="100"></div>
      </div>

    </header>

    <table class="calendar-table bg-white">

      <thead>

        <tr>
          <td>Sun</td>
          <td>Mon</td>
          <td>Tue</td>
          <td>Wed</td>
          <td>Thu</td>
          <td>Fri</td>
          <td>Sat</td>
        </tr>

      </thead>

      <tbody>

        <% @calendar_days.each do |week| %>
          <tr>
            <%= render partial: 'calendar_day', collection: week, as: :day %>
          </tr>
        <% end %>

      </tbody>

    </table>

  </div> <!-- end calendar -->

</div> <!-- end container -->

app/views/journals/new.html.erb
<br/>
<h1 class="text-center">New Journal</h1>

<%= render 'form', journal: @journal %>

app/views/journals/show.js.erb
var modal = new BS.Modal(document.getElementById('journalModal'));

$('#modal-journal-title').html("<%= j @journal.updated_at.strftime("%d/%m/%Y")  %>")

$('#modal-journal-body').html("<%= j render('show', journal: @journal) %>")

modal.toggle();