config/routes.rb
Rails.application.routes.draw do
  resources :journals
  resources :dashboards
  resources :tickets do
    resources :dailies
    resources :links
  end

  root 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :ticket

  def notes_truncated
    self.notes.truncate(NOTE_TRUNCATED_SIZE)
  end

  private
  NOTE_TRUNCATED_SIZE = 70
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :check_ticket
  before_action :set_daily, only: %i[ show edit update destroy ]
  after_action :update_ticket, only: %i[ create update destroy ]

  # GET /dailies or /dailies.json
  def index
    @today = DateTime.now.to_date
    @dailies = Daily.where(ticket_id: @ticket.id).order(updated_at: :desc)

    @dailies_map = @dailies.group_by { |d| d.updated_at.to_date } 
  end

  # GET /dailies/1 or /dailies/1.json
  def show
  end

  # GET /dailies/new
  def new
    @daily = Daily.new
  end

  # GET /dailies/1/edit
  def edit
  end

  # POST /dailies or /dailies.json
  def create
    @daily = Daily.new(daily_params)
    respond_to do |format|
      if @daily.save
        format.html { redirect_to ticket_dailies_url(@ticket), notice: "Daily was successfully created." }
        format.json { render :show, status: :created, location: @daily }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dailies/1 or /dailies/1.json
  def update
    respond_to do |format|
      if @daily.update(daily_params)
        format.html { redirect_to ticket_daily_url(@ticket, @daily), notice: "Daily was successfully updated." }
        format.json { render :show, status: :ok, location: @daily }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailies/1 or /dailies/1.json
  def destroy
    @daily.destroy
    respond_to do |format|
      format.html { redirect_to ticket_dailies_url(@ticket), notice: "Daily was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @daily = Daily.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_params
      params.require(:daily).merge(ticket_id: @ticket.id).permit(:notes, :ticket_id)
    end

    def check_ticket
      @ticket = Ticket.where(id: params[:ticket_id]).first
      if @ticket.nil?
        respond_to do |format|
          format.html { redirect_to tickets_path, notice: "Ticket does not exist." }
          format.json { render :index, status: :unprocessable_entity }
        end
      end
    end

    def update_ticket
      @daily.ticket.touch
    end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/views/dailies/_dailies_nav_panel.erb
<% dates = @dailies_map.keys %>

<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">

        <% dates.each do |date| %>
            <button class="nav-link <%= date == dates.first ? "active" : "" %>" id="nav-<%= date.to_s.gsub('-', '') %>-tab" data-bs-toggle="tab" data-bs-target="#nav-<%= date.to_s.gsub('-', '') %>" type="button" role="tab" aria-controls="nav-<%= date.to_s.gsub('-', '') %>" aria-selected="true"><%= date_ty_simplifier date %></button>
        <% end %>
    </div>
</nav>

<br>
<div class="tab-content" id="nav-tabContent">
    <% dates.each do |date| %>
        <div class="tab-pane fade show <%= date == dates.first ? "active" : "" %>" id="nav-<%= date.to_s.gsub('-', '') %>" role="tabpanel" aria-labelledby="nav-<%= date.to_s.gsub('-', '') %>-tab">
            <%= render 'daily_list_section', list: @dailies_map[date], has_actions: date == DateTime.now.to_date %>
        </div>
    <% end %>
</div>

app/views/dailies/_daily_list_section.erb
<table class="table table-striped bg-white">
  <thead>
    <tr>
      <th scope="col" class="text-center">Horário</th>
      <th scope="col">Nota</th>
      <% if has_actions %>
        <th scope="col" colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% list.each do |daily| %>
      <tr>
        <td class="text-center">
          <%= daily.updated_at.strftime("%H:%M") %></td>
        <td><%= link_to daily.notes_truncated, ticket_daily_url(@ticket.id, daily) %></td>
        <% if has_actions %>
          <td><%= link_to 'Editar', edit_ticket_daily_path(@ticket.id,daily), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to 'Excluir', ticket_daily_url(@ticket.id, daily), :data => {:confirm => 'Tem certeza que quer exluir essa nota?'}, :method => :delete, class: "btn btn-danger btn-sm" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dailies/_form.html.erb
<%= form_with(model: ticket_dailies, url: [@ticket, ticket_dailies]) do |form| %>
  <% if ticket_dailies.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily.errors.count, "error") %> prohibited this daily from being saved:</h2>

      <ul>
        <% @daily.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :notes, class: "form-label" %>
    <%= form.text_area :notes, class: "form-control big-text-area" %>
  </div>

  <br>

  <div class="actions d-grid gap-2">
    <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/dailies/edit.html.erb
<h1>Editing Daily</h1>

<%= render 'form', ticket_dailies: @daily %>

<br>
<div class="row">
    <div class="col-6 d-grid gap-2">
        <%= link_to 'Detalhes', ticket_daily_url(@ticket, @daily), class: "btn btn-primary" %> 
    </div>
    <div class="col-6 d-grid gap-2">
        <%= link_to 'Voltar', ticket_dailies_path(@ticket), class: "btn btn-primary" %>
    </div>
</div>

app/views/dailies/index.html.erb
<% unless notice == nil %>
  <div class="alert alert-primary alert-dismissible fade show" style="margin-top: 16px; margin-bottom: 16px;"role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<h1 class="text-center">Dailies - <%= link_to @ticket.name, @ticket %></h1>

<br>
<% unless @dailies.size == 0 %>
  <p><strong> Primeira nota: </strong><%= @dailies.last.updated_at.strftime("%d/%m/%Y") %> </p>
<% end %>
<% if @ticket.closed? %>
  <p><strong> Última nota: </strong><%= @dailies.first.updated_at.strftime("%d/%m/%Y") %> </p>
<% end %>
<p><strong> Duração do ticket: </strong><%= @ticket.past_days %> dias </p>
<p><strong> Número de notas: </strong><%= @dailies.size %> </p>

<hr />

<%= link_to 'Nova nota', new_ticket_daily_path, class: "btn btn-primary btn-sm" %>
<%= link_to 'Voltar', :back, class: "btn btn-primary btn-sm" %>

<br /><br />

<% if @dailies.empty? %>
  <h4>Sem registros</h4>
<% else %>
  <%= render 'dailies_nav_panel' %>
<% end %>

app/views/dailies/new.html.erb
<br>

<h1>Nova Nota</h1>

<%= render 'form', ticket_dailies: @daily %>

<br>

<div class="actions d-grid gap-2">
    <%= link_to 'Back', ticket_dailies_path(@ticket), class: 'btn btn-primary' %>
</div>

app/views/dailies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid py-5">
  <h1 class="display-5 fw-bold"><%= @ticket.name %></h1>
  <small class="text-muted">Data: <%= @daily.updated_at.strftime("%d/%m/%Y") %></small><br>
  <small class="text-muted">Hora: <%= @daily.updated_at.strftime("%H:%M ") %></small>
  <hr>
  <p class="col-md-8 fs-4"><%= @daily.notes %></p>
  <hr>
  
  <%= link_to 'Editar', edit_ticket_daily_path(@ticket, @daily), class: "btn btn-primary" %>
  <%= link_to 'Voltar', ticket_dailies_url(@ticket), class: "btn btn-primary" %>
  
</div>